=== Giza/retrotool/lib/templates/mp1r/root.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "properties": {
    "$schema": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "objects": {
      "type": "object",
      "patternProperties": {
        "0x[A-Fa-f0-9]{8}": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "typedefs": {
      "type": "object",
      "patternProperties": {
        "0x[A-Fa-f0-9]{8}": {
          "type": "string"
        }
      },
      "additionalProperties": false
    },
    "structs": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "enums": {
      "type": "array",
      "items": {
        "type": "string"
      }
    }
  },
  "required": [
    "name"
  ],
  "additionalProperties": false
}

=== Giza/retrotool/lib/templates/mp1r/root.json
{
  "$schema": "root.schema.json",
  "name": "Metroid Prime Remastered",
  "objects": {
    "0x749749f1": "Entity",
    "0x4ec5fa3a": "FakePlayerControls",
    "0x57153aa4": "StaticCollision",
    "0x41956904": "RenderWorld",
    "0xb4361e7b": "ActorCollision",
    "0x2be8bc19": "LightStatic",
    "0x9ee5541d": "LightDynamic",
    "0xcd098f70": "Effect",
    "0x8fe0bfc9": "Relay",
    "0xa7db53c1": "Counter",
    "0x9e8a4940": "Timer",
    "0xd616ee8b": "ControllerAction",
    "0xd898656d": "Waypoint",
    "0xf0240d23": "PathControl",
    "0x4fe57689": "CameraHint",
    "0x97e65ddd": "TouchableTrigger",
    "0x1a4117ab": "Touch",
    "0xc49d730e": "TriggerLogic",
    "0x1349e5ac": "CustomInterpolation",
    "0xc1f64515": "CameraTarget",
    "0xde522669": "Generator",
    "0x2c4f2d31": "SplineMotion",
    "0x21c57d2b": "DynamicActorCollision",
    "0xdf31ec16": "Render",
    "0xbde4ab05": "TakeDamage",
    "0x5453c979": "AnimationMountRider",
    "0x046fad23": "TimerSequence",
    "0x3175df36": "ApplyDamage",
    "0x65e2349b": "RelayRandom",
    "0xabbcfc6a": "RelayConditional",
    "0xea30e0b1": "SpawnPoint",
    "0x1fb9af22": "ActorKeyframe",
    "0x10ea9ec8": "ObjectFollow",
    "0x481ea5af": "Pickup",
    "0xbc9a60ae": "CameraManager",
    "0xb85d6790": "ColorModifier",
    "0x021c14b0": "Explosion",
    "0x16702f15": "ReloadSetLoader",
    "0x660fc7c1": "Checkpoint",
    "0x8c2ccfac": "PlayerRespawn",
    "0xc0281ae7": "ImpulseDriver",
    "0x06e89be7": "Health",
    "0x9373fec0": "Respawn",
    "0xc7b43da6": "ActorInteraction",
    "0x78d8893a": "CameraTargetPlayer",
    "0xce22001e": "PoiObject",
    "0xfdd83489": "Sound",
    "0xccad4bd9": "PerformanceGroupController",
    "0x502506d6": "TouchSet",
    "0xe1e1c49c": "LiquidVolume",
    "0x6c5d597d": "NearVisible",
    "0x3449a5df": "LiquidInhabitant",
    "0x591d8f55": "CharacterPrimitivesCollision",
    "0xbd4cfa2f": "TriggerForce",
    "0x2131c235": "GroupSpawn",
    "0x2751ebf2": "AnimationGridController",
    "0x18b96d29": "TimerAnimationGridParamProvider",
    "0x343a47f7": "CameraShaker",
    "0x7e6063c8": "PlayerActor",
    "0x91f22dcf": "Tippy",
    "0x89f426f2": "CinematicCameraShot",
    "0x1eb2749f": "ConveyorModifier",
    "0x73aecd92": "FogVolume",
    "0x845e492a": "Retronome",
    "0x23c5dff4": "WaterRenderVolume",
    "0x55f80cce": "CinematicSkipHandler",
    "0xf34edd1f": "InventoryItem",
    "0x18c0ad0f": "EndGame",
    "0x6302bbb3": "UVTransform",
    "0x25899782": "MusicData",
    "0x1ac8c8fd": "MusicStateController",
    "0x47a60dc3": "MusicSystemTransport",
    "0x5cf17bfe": "AdapterManager",
    "0x7f6d1cba": "RelayAutoFire",
    "0xd745dc42": "GraphicalTransition",
    "0x0fa3899c": "RetronomeDriver",
    "0xa7d1c922": "CausticVolume",
    "0xba796fef": "Playlist",
    "0x24d9d323": "VoiceEffect",
    "0xf7602744": "DSP",
    "0x160e9af9": "RoomSettings",
    "0x5746a908": "DynamicActorControl",
    "0xf442a668": "TimeKeyframe",
    "0xb6040870": "RelayProbabilityGameMode",
    "0x212bcdf5": "SimpleShadow",
    "0x655c5175": "AudioBusController",
    "0xf6751a5d": "PlayerKeyframe",
    "0x0be7fc29": "SurfaceControl",
    "0xb6ec1a51": "SimpleSound",
    "0xd2cac9a5": "LightGroupProxy",
    "0xbd040603": "LevelDarkener",
    "0xa72a9926": "RenderGroup",
    "0x3abcff68": "SkinSwap",
    "0xbff963d2": "StreamedMovie",
    "0x7dcaf170": "BloomEffect",
    "0x1243c3e3": "ProjectedSimpleShadowReceiver",
    "0x4c53a836": "LoadUnitController",
    "0xee0d6fd4": "DynamicLoadManager",
    "0x62913993": "AudioBusMixer",
    "0x8832ea4d": "FSMManager",
    "0x83cc17aa": "RoomController",
    "0xd0368513": "PathFind",
    "0xceafd99c": "OrbitTarget",
    "0x49bd721e": "NavigationMesh",
    "0x4490513e": "NavigationMeshHint",
    "0x85298bea": "NavigationOffMeshLink",
    "0xddea916d": "Tonemap",
    "0x8061e045": "ScreenSpaceAO",
    "0x38acaaf1": "TextPane",
    "0x79738030": "InventoryTextPane",
    "0x59cfbbd7": "ContextInteraction",
    "0x69091b92": "DetectionPlane",
    "0xb0c9b2f9": "CameraFilter",
    "0xad2098fa": "AnimatedMeter",
    "0x451740eb": "ModCon",
    "0xecd265d2": "GlobalStateMonitor",
    "0x91c301a5": "RelayMemory",
    "0xf05bc9c3": "EnvironmentVarModifier",
    "0x2ba4912d": "Terrain",
    "0x0998ffc9": "ControllerAnalogShapeAction",
    "0xb35b0375": "UICamera",
    "0x244019eb": "Drivable",
    "0xf6a30345": "Occlusion",
    "0xd8726471": "AnimatedSprite",
    "0xf06bbe92": "PlayerEventListener",
    "0x4c183ebb": "EnvironmentVarQuery",
    "0xc6f6f28c": "ControllerAnalogMovement",
    "0x91f73d69": "TriggerInhabitant",
    "0x09e806c4": "CameraTargetCreature",
    "0x013daaac": "UIButton",
    "0xb7332353": "ControllerAnalogInputDriver",
    "0x87efbcf0": "GradientAmbient",
    "0x59372fe6": "CameraSystemHint",
    "0xa3b90913": "CollisionProbe",
    "0xa02cf18f": "HUDSuppressor",
    "0x00c80ddc": "UIProxy",
    "0x70292d3d": "GameFlowRelay",
    "0x91666769": "SettingsMenuManager",
    "0xdec78ecb": "AnalogDriver",
    "0xc26abe1a": "EnvironmentVarSender",
    "0x2f0c8179": "EnvironmentVarListener",
    "0x29b7e32a": "ControlCommandDisabler",
    "0xf0d1bcc7": "ControlCommandSpoofer",
    "0x9e20d0af": "AiTarget",
    "0x2376de64": "UIRelay",
    "0x780e031e": "TriggerProgressionVolume",
    "0xb692d28b": "Projectile",
    "0x8f472283": "FrontEndManager",
    "0x455285e2": "RelayFrameDelay",
    "0x46b12081": "GameFlowHub",
    "0x676a5ac4": "NavigationAreaLink",
    "0x736dd919": "DamageResponderVulnerability",
    "0x10be69f9": "GameFlowProxy",
    "0xed02de02": "ObjectSelector",
    "0x55960d16": "AIGeneratorSelector",
    "0xac073df4": "AIGenerator",
    "0x78add45f": "Label",
    "0xf20f2698": "RelayAttackTypePayload",
    "0xafd50f72": "Faction",
    "0x3fcf5a88": "ParticleVolume",
    "0xb793d90a": "PeriodicAdditiveAnimationDriver",
    "0xd34ab306": "AnimVisibilityStateGroupManager",
    "0xcba2fc47": "PlayerDeathFall",
    "0x8b306e38": "SaveSlot",
    "0x8666855a": "CameraAdditiveFOV",
    "0xfd46f49e": "TriggerDeathFall",
    "0x5959db91": "RelayOriginatorFilter",
    "0xe1c825c9": "ObjectTeleport",
    "0x238467f5": "PlayerTeleport",
    "0x514043dd": "CameraPredictivePitchHint",
    "0xc338fd04": "PlayerInventoryEffects",
    "0x322f85e1": "CameraPredictiveYawHint",
    "0x067598be": "ToneData",
    "0x07edf6b2": "UIMenu",
    "0x3cfffc01": "UIWidget",
    "0x3dfd89f7": "RhythmMatcher",
    "0x8f4a3a35": "ToneSelectorSequence",
    "0xd0e99272": "ToneSelectorScriptDriven",
    "0xd298fc35": "CinematicActor",
    "0x7a6ed813": "SlideShow",
    "0x854924d1": "BoostPad",
    "0x7a38cc26": "SetInventory",
    "0x4adc88b7": "ToneSelectorHint",
    "0xb3b55602": "PathGenerator",
    "0x5445f685": "UIListView",
    "0x84bb17fa": "MIDINoteAdaptor",
    "0x3536e079": "NavigationMeshDynamicObstruction",
    "0xc16b7565": "CameraPointOfInterest",
    "0x41ad2545": "AITeleportProxy",
    "0xc9eebc83": "Cinematic",
    "0xd09fbbe7": "AABoxMagnet",
    "0xf9f62fd4": "FlowPath",
    "0x18e10190": "MIDISequence",
    "0x76aac155": "MIDIRetronome",
    "0x49d039cd": "ToneSelectorMIDI",
    "0xa10baa67": "Dock",
    "0xf190a097": "NavigationMeshDock",
    "0x6221a411": "GibManager",
    "0x0d3e0d14": "ScreenShot",
    "0x2249de78": "MIDIMatcher",
    "0xae579212": "ControllerMotionDriver",
    "0xd2bcb71a": "SetAnimVisibilityState",
    "0x21a978d3": "RenderClipPlane",
    "0x1955e30c": "IncandescenceModulator",
    "0x5f0fa37c": "UISlider",
    "0xcf9e2373": "SampleBankHint",
    "0xfc397b56": "AudioSamplerProxy",
    "0x57ab06b5": "SubtitleSequence",
    "0x00921362": "PhaseToEvents",
    "0xc6c04116": "SplineMotionPhaseResponder",
    "0x35fa03a6": "ActorKeyframePhaseResponder",
    "0xf3bc4ee8": "SimpleSoundPhaseResponder",
    "0x4ca2e586": "MIDINoteEmitter",
    "0x05dd288e": "Boolean",
    "0x9340932c": "LogicGate",
    "0xd7b10efd": "RenderDecal",
    "0xdf279c9b": "PatternMatcher",
    "0x9d97d9c1": "MIDIControllerMessageEmitter",
    "0xc03cd39d": "SoundVolumeModifier",
    "0xf75add4d": "Reactivator",
    "0x8be6648a": "SampleBankData",
    "0xe795d2b1": "ActionControlPoint",
    "0xa86001c4": "MusicStateTransitionData",
    "0x74bd547a": "Footprint",
    "0x61ef47c6": "SamplerVoiceBankData",
    "0x916f072f": "PlayerSpawnTeleporter",
    "0x17982019": "AudioSampleBank",
    "0xdc777c06": "AudioSampler",
    "0xea6d58e8": "HardwareProxy",
    "0xb2da6936": "RoomPreloader",
    "0x0ef9abe4": "BroadcastSpatialListener",
    "0x9aafcb03": "BroadcastSpatial",
    "0xd515e89d": "AudioBusDriver",
    "0x2c9918ae": "AudioBusDriverInteractor",
    "0x1a4bc6bd": "CombatStateProxy",
    "0xe6a64862": "MIDITransmitter",
    "0x4f10becb": "MIDIReceiver",
    "0xf12e9c71": "MIDIResponderSampler",
    "0x3325a532": "RuleSetManager",
    "0xd9c9a3f5": "MIDIResponderArpeggiator",
    "0xba249e78": "MIDIResponderChordMaker",
    "0xd645278a": "TemplateManager",
    "0x11f81321": "MIDIResponderPatternMatcher",
    "0xd813a35a": "AddActorEntityFlag",
    "0x12931ce3": "ColorSampler",
    "0x057dc20f": "PickupManager",
    "0xd3fd952c": "SoundPitchModifier",
    "0x75560ce3": "ActorVertexAnimationPlayList",
    "0x412e0d82": "ActorVertexAnimationPhaseResponder",
    "0x5cb0de9c": "BGMHint",
    "0x37e758da": "LightShafts",
    "0x8ce59f27": "Choreographer",
    "0xd7c7e6f9": "RelayChoreography",
    "0xd54b0dcc": "AudioSamplerPhaseResponder",
    "0x8ce6e4f6": "PhaseLooper",
    "0x945e0902": "CameraLetterBox",
    "0x27807e39": "ReflectionProbe",
    "0xd008829f": "HeatDistortionHint",
    "0x5e3f39ee": "CameraProxy",
    "0xf75ea7ef": "LavaFlowSurface",
    "0x92561a4a": "FogShape",
    "0xae371a20": "DockDoor",
    "0xcc8f9ff2": "GenericSplineControl",
    "0x00682591": "ControlSplineMappingsDefinition",
    "0x157533dd": "Scannable",
    "0xc04d4753": "PhaseRelay",
    "0x5112a065": "Skybox",
    "0x0637e29a": "ControlSchemesDefinition",
    "0x60e107e0": "ControlSchemeAccessor",
    "0xece8e32e": "AudioObstruction",
